FROM chestereck/nana:aosp

RUN git config --global user.name "leon4rd"
RUN git config --global user.email "apalotega02@gmail.com"
RUN git config --global credential.helper store

RUN sudo apt update -y
RUN sudo apt upgrade -y

RUN sudo apt install wget -y
