name: Docker Build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_UNAME }}
        password: ${{ secrets.DH_TOKEN }}
    - name: Build and Publish to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.github/workflows/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DH_UNAME }}/nana:latest
        
    - name: send telegram message
      run: |
          function sendTG() {
          curl -s "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendmessage" --data "text=${*}&chat_id=${{ secrets.TG_CHAT }}&parse_mode=Markdown"
          }
          sendTG "\`I have pushed new images to docker\` %0A [Image are here](https://hub.docker.com/r/${{ secrets.DH_UNAME }}/nana/tags)" &> /dev/null
